USUARIO_DB = 'postgres'
SENHA_DB = 'admin'
HOST_DB = 'localhost'
PORTA_DB = '5432'
NOME_DB = 'SCQP'

SQLALCHEMY_DATABASE_URI = f'postgresql://{USUARIO_DB}:{SENHA_DB}@{HOST_DB}:{PORTA_DB}/{NOME_DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
